name: Build and Deploy JAR to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests
        working-directory: ./demo/demo

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # ✅ Updated to v4
        with:
          name: java-app
          path: ./demo/demo/target/demo-0.0.1-SNAPSHOT.jar
          retention-days: 1  # Optional, keeps artifact for 1 day

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4  # ✅ Updated to v4
        with:
          name: java-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: 'SERVICE_PRINCIPAL'

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'GrizSportsSB'
          package: './target/demo-0.0.1-SNAPSHOT.jar'
          startup-command: 'java -jar -Dserver.port=$PORT /home/site/wwwroot/demo-0.0.1-SNAPSHOT.jar'
