name: Build and Deploy JAR to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '21'  # Choose your Java version
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests
        working-directory: ./demo/demo

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: ./demo/demo/target/demo-0.0.1-SNAPSHOT.jar  # Adjust path if needed

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures deployment runs only after build succeeds
    environment:
      name: 'Production'  # Make sure this matches your GitHub Environment
    permissions:
      id-token: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: java-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}  # Set this in GitHub secrets
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}  # Set this in GitHub secrets
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  # Set this in GitHub secrets
          auth-type: 'SERVICE_PRINCIPAL'

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'GrizSportsSB'
          package: 'demo-0.0.1-SNAPSHOT.jar'  # Make sure this matches your JAR filename
          startup-command: 'java -jar /home/site/wwwroot/demo-0.0.1-SNAPSHOT.jar'
